#!/bin/sh

PATH=${PWD%code*}code:$PATH

pngnogamma () {
  priforgepng -d 2 glr rbr gtb -s 8 | priweavepng - - -
}

# Check no gAMA chunk first, then add one and check again
pngnogamma | pripnglsch | grep -q gAMA && exit 9
pngnogamma | prichunkpng --gamma 0.45 - |
  pripnglsch |
  grep -q gAMA
